import os
from fontforge import *

# font = open(os.sys.argv[1])
font = open('./fz.ttf')
for glyph in font:
    if font[glyph].isWorthOutputting():
    	# font[glyph].export("./fz_bmp/"+str(font[glyph].unicode)+"_"+font[glyph].glyphname + ".bmp")
    	if(font[glyph].glyphname=="A"):
    		print(font[glyph].unicode)
    		print(font[glyph].foreground)
    		print(font[glyph].activeLayer)
    		print(font[glyph].anchorPoints)
    		print(font[glyph].background)
    		print(font[glyph].changed)
    		print(font[glyph].color)
    		print(font[glyph].comment)
    		print(font[glyph].dhints)
    		print(font[glyph].hhints)
    		print(font[glyph].horizontalComponents)
    		print(font[glyph].horizontalComponentItalicCorrection)
    		print(font[glyph].horizontalVariants)
    		print(font[glyph].layer_cnt)
    		print(font[glyph].lcarets)
    		print("left",font[glyph].left_side_bearing)
    		print(font[glyph].mathKern.bottomLeft)
    		print(font[glyph].originalgid)
    		print(font[glyph].persistent)
    		print(font[glyph].references)
    		print(font[glyph].right_side_bearing)
    		print(font[glyph].script)
    		print(font[glyph].texheight)
    		print(font[glyph].texdepth)
    		print(font[glyph].width)
    		print(font[glyph].vwidth)
    		

font = open('./output.ttf')
for glyph in font:
    if font[glyph].isWorthOutputting():
    	# font[glyph].export("./fz_bmp/"+str(font[glyph].unicode)+"_"+font[glyph].glyphname + ".bmp")
    	if(font[glyph].glyphname=="A"):
    		print(font[glyph].unicode)
    		print(font[glyph].foreground)
    		print(font[glyph].activeLayer)
    		print(font[glyph].anchorPoints)
    		print(font[glyph].background)
    		print(font[glyph].changed)
    		print(font[glyph].color)
    		print(font[glyph].comment)
    		print(font[glyph].dhints)
    		print(font[glyph].hhints)
    		print(font[glyph].horizontalComponents)
    		print(font[glyph].horizontalComponentItalicCorrection)
    		print(font[glyph].horizontalVariants)
    		print(font[glyph].layer_cnt)
    		print(font[glyph].lcarets)
    		print("left",font[glyph].left_side_bearing)
    		print(font[glyph].mathKern.bottomLeft)
    		print(font[glyph].originalgid)
    		print(font[glyph].persistent)
    		print(font[glyph].references)
    		print(font[glyph].right_side_bearing)
    		print(font[glyph].script)
    		print(font[glyph].texheight)
    		print(font[glyph].texdepth)
    		print(font[glyph].width)
    		print(font[glyph].vwidth)
